/* empty css                      */import{a as L,i as f,S as w}from"./assets/vendor-BM5befbE.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const v=document.getElementById("search-form"),b=document.getElementById("search-input"),u=document.getElementById("gallery"),l=document.getElementById("loader"),a=document.querySelector(".load-more"),h=document.querySelector(".end-message");let d;const E="53016082-e520ad17d921b98237d23020b",S="https://pixabay.com/api/";let p="",i=1;const m=40;let g=0;v.addEventListener("submit",async r=>{r.preventDefault();const t=b.value.trim();t&&(p=t,i=1,u.innerHTML="",h.classList.add("hidden"),a.classList.add("hidden"),await y())});a.addEventListener("click",async()=>{i++,await y(!0)});async function y(r=!1){l.classList.remove("hidden");try{const n=(await L.get(S,{params:{key:E,q:p,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:m}})).data;if(l.classList.add("hidden"),n.hits.length===0){f.error({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),a.classList.add("hidden");return}g=n.totalHits,B(n.hits,r),P(n.hits.length),I(r)}catch(t){l.classList.add("hidden"),f.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(t)}}function B(r,t=!1){const n=r.map(s=>`
    <a class="card" href="${s.largeImageURL}">
      <img src="${s.webformatURL}" alt="${s.tags}" />
      <div class="card-info">
        <p>Likes: ${s.likes} | Views: ${s.views}</p>
        <p>Comments: ${s.comments} | Downloads: ${s.downloads}</p>
      </div>
    </a>
  `).join("");t?u.insertAdjacentHTML("beforeend",n):u.innerHTML=n,d?d.refresh():d=new w(".gallery a",{captionsData:"alt",captionDelay:250})}function P(r){i*m>=g||r<m?(a.classList.add("hidden"),h.classList.remove("hidden")):a.classList.remove("hidden")}function I(r){if(!r)return;const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
